name: Go Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      test_files: ${{ steps.tests.outputs.test_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Find Go test files
        id: tests
        run: |
          TEST_FILES=$(go list -json ./... | jq -r '.ImportPath' | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "test_files=$TEST_FILES" >> "$GITHUB_ENV"

      - name: Save output
        run: echo "test_files=${{ env.test_files }}" >> "$GITHUB_ENV"

  test:
    needs: checkout
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: ${{ fromJson(env.test_files) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run test
        run: |
          go test ${{ matrix.test_file }} -v
